import {
  ApplicationConfig,
  provideBrowserGlobalErrorListeners,
  importProvidersFrom,
  isDevMode,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import {
  LucideAngularModule,
  AlertTriangle,
  Asterisk,
  BookOpen,
  Building2,
  Calculator,
  Calendar,
  Captions,
  CaptionsOff,
  Check,
  ChevronDown,
  Copy,
  Dock,
  DollarSign,
  Eye,
  EyeOff,
  FileText,
  Home,
  HousePlus,
  Lock,
  LogOut,
  Mail,
  Pencil,
  Phone,
  PhoneCall,
  Plus,
  QrCode,
  Search,
  Trash2,
  Truck,
  Type,
  User,
  Users,
} from 'lucide-angular';

import { routes } from './app.routes';
import { provideServiceWorker } from '@angular/service-worker';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    importProvidersFrom(
      LucideAngularModule.pick({
        AlertTriangle,
        Asterisk,
        BookOpen,
        Building2,
        Calculator,
        Calendar,
        Captions,
        CaptionsOff,
        Check,
        ChevronDown,
        Copy,
        Dock,
        DollarSign,
        Eye,
        EyeOff,
        FileText,
        Home,
        HousePlus,
        Lock,
        LogOut,
        Mail,
        Pencil,
        Phone,
        PhoneCall,
        Plus,
        QrCode,
        Search,
        Trash2,
        Truck,
        Type,
        User,
        Users
      }),
    ),
    provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000',
    }),
  ],
};
